default: &default
  appid:  <%= Figaro.env.wechat_app_id %>
  secret: <%= Figaro.env.wechat_secret %>
  token:  <%= Figaro.env.wechat_token %>

production:
  <<: *default
  encoding_aes_key: <%= Figaro.env.wechat_encoding_aes_key %>
  encrypt_mode: true

development:
  <<: *default
  encoding_aes_key: <%= Figaro.env.wechat_encoding_aes_key %>
  encrypt_mode: true
  trusted_domain_fullname: <%= Figaro.env.wechat_trusted_domain_fullname %>
  access_token: <%= Figaro.env.access_token %>

test:
  <<: *default
  access_token: "/tmp/wechat_starter_test_access_token"
  jsapi_ticket: "/tmp/wechat_starter_test_jsapi_ticket"
